<?php
use Illuminate\Support\Facades\Route;use App\Http\Controllers\AuthController;use App\Http\Controllers\DashboardController;use App\Http\Controllers\ServiceController;use App\Http\Controllers\BookingController;use App\Http\Controllers\ReviewController;use App\Http\Controllers\PaymentController;
Route::get('/',fn()=>redirect()->route(auth()->check()?'dashboard':'login'));
Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'showLogin'])->name('login');Route::post('/login',[AuthController::class,'login'])->name('login.store');Route::get('/register',[AuthController::class,'showRegister'])->name('register');Route::post('/register',[AuthController::class,'register'])->name('register.store');});
Route::post('/logout',[AuthController::class,'logout'])->middleware('auth')->name('logout');
Route::middleware('auth')->group(function(){Route::get('/dashboard',[DashboardController::class,'index'])->name('dashboard');Route::get('/services',[ServiceController::class,'index'])->name('services.index');Route::get('/services/{service}',[ServiceController::class,'show'])->name('services.show');Route::get('/bookings',[BookingController::class,'index'])->middleware('role:customer')->name('bookings.index');Route::post('/bookings',[BookingController::class,'store'])->middleware('role:customer')->name('bookings.store');Route::get('/bookings/{booking}',[BookingController::class,'show'])->name('bookings.show');Route::post('/bookings/{booking}/cancel',[BookingController::class,'cancel'])->middleware('role:customer')->name('bookings.cancel');Route::post('/bookings/{booking}/review',[ReviewController::class,'store'])->middleware('role:customer')->name('reviews.store');Route::get('/payments/{booking}',[PaymentController::class,'show'])->middleware('role:customer')->name('payments.show');
Route::post('/payments/{booking}',[PaymentController::class,'pay'])->middleware('role:customer')->name('payments.pay');
Route::prefix('admin')->name('admin.')->middleware('role:admin')->group(function(){Route::resource('categories',\App\Http\Controllers\Admin\CategoryController::class)->except(['create','edit','show']);Route::resource('services',\App\Http\Controllers\Admin\ServiceController::class)->except(['create','edit','show']);Route::resource('users',\App\Http\Controllers\Admin\UserController::class)->only(['index','update']);Route::resource('bookings',\App\Http\Controllers\Admin\BookingController::class)->only(['index','update']);});
Route::prefix('provider')->name('provider.')->middleware('role:provider')->group(function(){Route::resource('services',\App\Http\Controllers\Provider\ServiceController::class)->except(['create','edit','show']);Route::resource('bookings',\App\Http\Controllers\Provider\BookingController::class)->only(['index','update']);});
});
